# Generated by Django 5.1.3 on 2024-11-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='notes/background'),
        ),
    ]
